### ISSUE TITLE
Open ended dependencies

### ISSUE THREAD

**Issue by electrical** [nibalizer/metadata-json-lint#6]
Would be cool if we could check for open ended dependencies like the Forge does for the scoring.

**Comment by electrical** [comment]
Should be implemented with #9

**Comment by otheus** [comment]
I have the same issue as reported here: https://github.com/dfarrell07/puppet-opendaylight/issues/18

" Dependency vcsrepo has an open ended dependency version requirement >= 1.0.0"

```
  "dependencies": [
    { "name":"vcsrepo", "version_requirement":">= 1.0.0" }
  ]
```

**Comment by nibalizer** [comment]
I rolled back #9. Sorry @electrical it created a bunch of problems. We really need puppetlabs to release the semantic lib as a gem.
